#define DLLWRPJMP(x) void __declspec(dllimport) x(); void DllWrapper_Jump__##x() { x(); } __pragma(comment(linker, "/export:" #x "=" "DllWrapper_Jump__" #x))

#pragma comment(linker, "/BASE:0x7FF37320000")

DLLWRPJMP(DllCanUnloadNow)
DLLWRPJMP(DllGetClassObject)
DLLWRPJMP(Private1)
DLLWRPJMP(SvchostPushServiceGlobals)
DLLWRPJMP(WinHttpAddRequestHeaders)
DLLWRPJMP(WinHttpAutoProxySvcMain)
DLLWRPJMP(WinHttpCheckPlatform)
DLLWRPJMP(WinHttpCloseHandle)
DLLWRPJMP(WinHttpConnect)
DLLWRPJMP(WinHttpCrackUrl)
DLLWRPJMP(WinHttpCreateUrl)
DLLWRPJMP(WinHttpDetectAutoProxyConfigUrl)
DLLWRPJMP(WinHttpGetDefaultProxyConfiguration)
DLLWRPJMP(WinHttpGetIEProxyConfigForCurrentUser)
DLLWRPJMP(WinHttpGetProxyForUrl)
DLLWRPJMP(WinHttpOpen)
DLLWRPJMP(WinHttpOpenRequest)
DLLWRPJMP(WinHttpQueryAuthSchemes)
DLLWRPJMP(WinHttpQueryDataAvailable)
DLLWRPJMP(WinHttpQueryHeaders)
DLLWRPJMP(WinHttpQueryOption)
DLLWRPJMP(WinHttpReadData)
DLLWRPJMP(WinHttpReceiveResponse)
DLLWRPJMP(WinHttpSendRequest)
DLLWRPJMP(WinHttpSetCredentials)
DLLWRPJMP(WinHttpSetDefaultProxyConfiguration)
DLLWRPJMP(WinHttpSetOption)
DLLWRPJMP(WinHttpSetStatusCallback)
DLLWRPJMP(WinHttpSetTimeouts)
DLLWRPJMP(WinHttpTimeFromSystemTime)
DLLWRPJMP(WinHttpTimeToSystemTime)
DLLWRPJMP(WinHttpWriteData)